
stages:
  - test
  - build
  - deploy

before_script:
  - echo 'yarn-offline-mirror ".yarn-cache/"' >> .yarnrc
  - echo 'yarn-offline-mirror-pruning true' >> .yarnrc

test:
  stage: test
  image: node:16-alpine
  cache:
    key: 
      files:
        - yarn.lock
    paths:
      - .yarn-cache/
  script:
    - yarn install --frozen-lockfile --no-progress
    - yarn lint
    - yarn test

build:
  stage: build
  image: docker
  services:
    - docker:dind
  cache:
    key: 
      files:
        - yarn.lock
    paths:
      - .yarn-cache/
  only:
    refs:
      - develop
  before_script:
    - mkdir -p ~/.docker
    - cp $REGISTRY_DG_AUTH ~/.docker/config.json
  script:
    - docker build -t ${REGISTRY_PATH}/next-seed .
    - docker push ${REGISTRY_PATH}/next-seed

deploy:
  image: bitnami/kubectl
  stage: deploy
  only:
    refs:
      - develop
  script:
    - kubectl rollout restart deployment next-seed-api -n next-seed-ns








