stages:
  - test
  - build
  - deploy

test:
  stage: test
  image: node:16-alpine
  cache:
    paths:
      - node_modules/
  only:
    refs:
      - merge_requests
  script:
    - yarn install --frozen-lockfile
    - yarn lint
    - yarn test

build:
  stage: build
  image: docker
  only:
    refs:
      - develop
  before_script:
    - mkdir -p ~/.docker
    - cp $REGISTRY_DG_AUTH ~/.docker/config.json
  script:
    - docker build -t ${REGISTRY_PATH}/next-seed .
    - docker push ${REGISTRY_PATH}/next-seed

deploy:
  image: bitnami/kubectl
  stage: deploy
  only:
    refs:
      - develop
  script:
    - kubectl rollout restart deployment next-seed -n next-seed-ns
